version: "3.7"

services:

  # Imagem Aplicação
  app:
    build:
      context: ./docker/php/
      dockerfile: Dockerfile
    image: app-php81
    container_name: simple-project-app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - network-project

  nginx:
    image: nginx:1.17-alpine
    container_name: simple-project-nginx
    restart: unless-stopped
    ports:
      - "8001:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
    networks:
      - network-project

# Network Project
networks:
  network-project:
    driver: bridge